import type { Question } from '@/types'

export const questions: Question[] = [
  {
    id: 'q1',
    number: 1,
    type: 'checkbox',
    text: 'MIGAQに通う目的は何ですか？',
    subtext: '複数選択可',
    options: [
      '歯を白くしたい',
      '眉毛を整えたい',
      '清潔感を上げたい',
      '垢抜けたい',
      'モテたい',
      '恋愛に自信をつけたい',
      '仕事で好印象になりたい',
      '自信をつけたい',
    ],
    hasOtherOption: true,
  },
  {
    id: 'q2',
    number: 2,
    type: 'rating-with-text',
    text: 'MIGAQの満足度を教えてください',
    options: ['非常に満足', '満足', '普通', 'やや不満', '不満'],
  },
  {
    id: 'q3',
    number: 3,
    type: 'checkbox',
    text: '今後あったら嬉しいサービスを教えてください',
    subtext: '複数選択可',
    options: [
      'AI印象診断',
      'スキンケア相談',
      'ヘアスタイル相談',
      'ファッション相談',
      '恋愛向け印象改善',
      '営業向け印象改善',
      '会員限定イベント',
      '会員限定交流会',
    ],
    hasOtherOption: true,
  },
  {
    id: 'q4',
    number: 4,
    type: 'radio',
    text: '月1回の会員限定Zoomがあれば参加したいですか？',
    options: [
      'ぜひ参加したい',
      '内容次第で参加したい',
      'アーカイブだけ見たい',
      '興味がない',
    ],
  },
  {
    id: 'q5',
    number: 5,
    type: 'checkbox',
    text: '参加したいテーマを教えてください',
    subtext: '複数選択可',
    options: [
      '第一印象改善',
      'モテる清潔感',
      '恋愛',
      '営業',
      'コミュニケーション力',
      '自己紹介力',
      '自信のつけ方',
      'メンズ美容',
      'AI活用',
    ],
    hasOtherOption: true,
  },
  {
    id: 'q6',
    number: 6,
    type: 'checkbox',
    text: 'もしMIGAQを解約するとしたら理由は何ですか？',
    subtext: '複数選択可',
    options: [
      '料金',
      '通う時間がない',
      '効果に満足した',
      '必要性を感じなくなった',
      'サービス内容',
      '他店を利用する',
    ],
    hasOtherOption: true,
  },
  {
    id: 'q7',
    number: 7,
    type: 'textarea',
    text: 'どんなサービスがあれば継続したいと思いますか？',
    subtext: '自由にお書きください',
  },
  {
    id: 'q8',
    number: 8,
    type: 'textarea',
    text: 'MIGAQへのご意見・ご要望',
    subtext: '自由にお書きください',
  },
]

export const TOTAL_QUESTIONS = questions.length
